# version: '3.7'
# services:
#   api:
#     build: .
#     volumes:
#       - .:/app
#     ports:
#       - "3000:3000"
#     depends_on:
#       - postgres
#   postgres:
#     image: postgres:11.1
#     ports:
#       - "5432:5432"
#
version: '3.7'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
volumes:
  pgdata:
